-- Conformed date dimension. Generated by the pipeline, not loaded from f1_prod -- see
-- etl/pipeline/load.py, which populates it from generate_series on every run.
-- Every attribute here is derivable from full_date. That redundancy is the point of a date
-- dimension: the labels are defined once, and no query re-derives them per row.
CREATE TABLE IF NOT EXISTS dim_date (
    date_key     INTEGER      PRIMARY KEY,              -- YYYYMMDD, e.g. 20240315
    full_date    DATE         NOT NULL UNIQUE,
    year         SMALLINT     NOT NULL,
    quarter      SMALLINT     NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    month        SMALLINT     NOT NULL CHECK (month BETWEEN 1 AND 12),
    month_name   VARCHAR(10)  NOT NULL,                 -- 'January' .. 'December'
    week_of_year SMALLINT     NOT NULL,                 -- ISO week 1-53
    day_of_week  SMALLINT     NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),  -- 0 = Sunday, matching EXTRACT(DOW)
    day_name     VARCHAR(10)  NOT NULL,                 -- 'Sunday' .. 'Saturday'
    is_weekend   BOOLEAN      NOT NULL
);

-- week_of_year is the ISO week, whose ISO year is not always the calendar year: 1994-01-01 is
-- ISO week 52 of 1993. Two rows in this range are affected and no view groups by week, so the
-- column is left as-is -- but do not group by (year, week_of_year).
COMMENT ON COLUMN dim_date.week_of_year IS 'ISO week 1-53. ISO year can differ from year at January boundaries; do not group by (year, week_of_year).';
